[project]
site_name = "The MERC Project"
site_url = "https://MERCorg.github.io/merc-website/"
repo_url = "https://github.com/MERCorg/merc/"
repo_name = "MERCorg/merc"

extra_css = ["stylesheets/extra.css"]

nav = [
  { Home = "index.md" },
  { Tools = [
    "tools/reordering.md",
  ] },
  { Development = [
    "developer/general.md",
    "developer/testing.md",
    "developer/documentation.md",
    { "Symmetry" = [
      "developer/symmetry/symmetry-detection-graph.md",
      "developer/symmetry/canonicalize-orbit.md",
    ] },
    { "Rewriting" = [
      "developer/rewriting/aterms.md",
      "developer/rewriting/set-automaton.md",
      "developer/rewriting/machine-numbers.md",
      "developer/rewriting/condition-caching.md",
      "developer/rewriting/lowering.md",
      "developer/rewriting/enumeration.md",
      "developer/rewriting/one-point-rewriter.md",
    ] },
    { "Parsing" = [
      "developer/parsing/disambiguation.md",
      "developer/parsing/performance.md",
      "developer/parsing/precedence.md",
      "developer/parsing/source_map.md",
    ] },
    { "Type Checking" = [
      "developer/typechecking/index.md",
      "developer/typechecking/name-resolution.md",
      "developer/typechecking/desugaring.md",
      "developer/typechecking/signature.md",
      "developer/typechecking/system-specification.md",
      "developer/typechecking/polymorphism.md",
      "developer/typechecking/sort-inference.md",
      "developer/typechecking/inference/unification.md",
      "developer/typechecking/inference/solver.md",
      "developer/typechecking/typing-info.md",
    ] },
    { "Specification" = [
      "developer/specification/index.md",
    ] },
    { "Symbolic" = [
      "developer/symbolic/saturation.md",
      "developer/symbolic/zielonka.md",
      "developer/symbolic/partial-solving.md",
    ] },
    { "Linearisation" = [
      "developer/linearisation/index.md",
    ] },
  ] },
  { Maintainers = [
    "maintainers/publishing.md",
  ] },
  { Links = [
    { "Issue Tracker" = "https://github.com/MERCorg/merc/issues" },
    { Documentation = "https://MERCorg.github.io/merc/" },
    { Coverage = "https://MERCorg.github.io/merc/coverage/" },
  ] },
]

[project.theme]
language = "en"
features = [
  "navigation.instant",
]

[[project.theme.palette]]
scheme = "slate"
primary = "amber"
accent = "amber"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "default"
primary = "amber"
accent = "amber"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.highlight]
use_pygments = true
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.latex_math]
